# -*- coding: utf-8 -*-
"""sumipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ni9Mkj_m6gEr7blb_oE6V9K3xncZ2NDI
"""

!pip install pymupdf python-docx scikit-learn numpy google-generativeai

# ============================================
# MAIN CODE - AI Learning Notes Simplifier
# ============================================

import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import TfidfVectorizer
from google.colab import files
import google.generativeai as genai
import os
import fitz                 # pymupdf - for PDF
from docx import Document   # python-docx - for Word

# ============================================
# 🔑 REPLACE YOUR GEMINI API KEY HERE
# Get free key from: https://aistudio.google.com/app/apikey
# ============================================
GEMINI_API_KEY = "AIzaSyARcHxHxieuRO7c0JDdufxAOA3aPcRsdwc"
genai.configure(api_key=GEMINI_API_KEY)
model = genai.GenerativeModel("gemini-2.5-flash")

# ============================================
# Knowledge Base
# ============================================
knowledge_base = [
    {"term": "Context Compression",  "simple": "Like summarizing a long book into a short paragraph."},
    {"term": "Retrieval",            "simple": "Like using a search engine inside your notes."},
    {"term": "Prompt Augmentation",  "simple": "Like giving extra hints before asking a question."},
    {"term": "Similarity Search",    "simple": "Like finding songs that sound alike using math."},
    {"term": "Embedding",            "simple": "Like turning words into GPS coordinates."},
    {"term": "Neural Network",       "simple": "Like a brain made of math — learns from examples."},
    {"term": "Transformer",          "simple": "Like a very attentive reader of all words at once."},
    {"term": "Fine-tuning",          "simple": "Like teaching a general doctor to become a specialist."},
    {"term": "Tokenization",         "simple": "Like cutting a sentence into Lego pieces."},
    {"term": "Attention Mechanism",  "simple": "Like highlighting the most important words."},
    {"term": "Gradient Descent",     "simple": "Like finding the lowest point by taking small steps downhill."},
    {"term": "Overfitting",          "simple": "Like memorizing exam answers without understanding."},
]

# ============================================
# File Reading Functions
# ============================================
def read_txt_file(filepath):
    with open(filepath, 'r', encoding='utf-8', errors='ignore') as f:
        return f.read()

def read_pdf_file(filepath):
    text = ""
    doc = fitz.open(filepath)
    print(f"   📄 PDF has {len(doc)} page(s)")
    for page_num, page in enumerate(doc):
        text += f"\n--- Page {page_num + 1} ---\n{page.get_text()}"
    doc.close()
    return text.strip()

def read_docx_file(filepath):
    doc = Document(filepath)
    text = ""
    for para in doc.paragraphs:
        if para.text.strip():
            text += para.text + "\n"
    for table in doc.tables:
        for row in table.rows:
            row_text = " | ".join(cell.text.strip() for cell in row.cells if cell.text.strip())
            if row_text:
                text += row_text + "\n"
    return text.strip()

def read_file(filepath):
    ext = os.path.splitext(filepath)[1].lower()
    print(f"   🔎 File type detected: {ext.upper()}")
    if ext == '.pdf':
        return read_pdf_file(filepath)
    elif ext == '.docx':
        return read_docx_file(filepath)
    elif ext in ['.txt', '.md', '.csv', '.json', '.log', '.py']:
        return read_txt_file(filepath)
    else:
        print(f"   ⚠️ Unknown type, trying as plain text...")
        return read_txt_file(filepath)

# ============================================
# Similarity Search
# ============================================
def build_vectorizer(knowledge_base):
    texts = [f"{item['term']} {item['simple']}" for item in knowledge_base]
    vectorizer = TfidfVectorizer()
    vectors = vectorizer.fit_transform(texts)
    return vectorizer, vectors

def retrieve_relevant_context(query, knowledge_base, vectorizer, vectors, top_k=3):
    query_vec = vectorizer.transform([query])
    similarities = cosine_similarity(query_vec, vectors)[0]
    top_indices = np.argsort(similarities)[::-1][:top_k]
    retrieved = []
    for idx in top_indices:
        if similarities[idx] > 0:
            retrieved.append({
                "term": knowledge_base[idx]["term"],
                "analogy": knowledge_base[idx]["simple"],
                "score": round(float(similarities[idx]), 3)
            })
    return retrieved

# ============================================
# Context Compression
# ============================================
def compress_context(retrieved_items):
    if not retrieved_items:
        return "No specific analogies found."
    compressed = "Relevant simple analogies:\n"
    for item in retrieved_items:
        compressed += f"• {item['term']}: {item['analogy']}\n"
    return compressed.strip()

# ============================================
# Summarize using FREE Gemini API
# ============================================
def simplify_and_summarize(file_content, knowledge_base, vectorizer, vectors):
    content_preview = file_content[:4000]
    if len(file_content) > 4000:
        print("   ⚠️ Large file — using first 4000 characters")

    print("🔍 Retrieving relevant analogies...")
    retrieved = retrieve_relevant_context(content_preview[:500], knowledge_base, vectorizer, vectors)

    print("📦 Compressing context...")
    compressed_context = compress_context(retrieved)

    print("🤖 Sending to Gemini for summarization...")

    augmented_prompt = f"""You are a helpful teacher who simplifies complex content for beginners.

Here are some simple analogies that may be relevant:
{compressed_context}

Below is content from an uploaded file. Your job is to:
1. Write a SHORT SUMMARY (5-8 bullet points max)
2. Use simple beginner-friendly language
3. Highlight KEY POINTS only
4. Use analogies where relevant
5. Avoid jargon — explain any technical terms simply

File Content:
\"\"\"
{content_preview}
\"\"\"

Short Summary (beginner-friendly):"""

    response = model.generate_content(augmented_prompt)

    return {
        "retrieved_analogies": retrieved,
        "summary": response.text
    }

# ============================================
# Upload File & Run
# ============================================
print("=" * 60)
print("   📁 AI LEARNING NOTES SIMPLIFIER - GEMINI VERSION")
print("   Supports: .txt | .md | .pdf | .docx | .csv | .json")
print("=" * 60)
print("\n👆 Upload your file below:\n")

uploaded = files.upload()

if not uploaded:
    print("❌ No file uploaded.")
else:
    filename = list(uploaded.keys())[0]
    file_size = len(uploaded[filename])
    print(f"\n✅ File uploaded: {filename}")
    print(f"   📦 Size: {file_size:,} bytes ({file_size/1024:.1f} KB)\n")

    print("📖 Reading file...")
    file_content = read_file(filename)

    if not file_content.strip():
        print("❌ No text found in file.")
    else:
        print(f"   ✅ Extracted {len(file_content):,} characters\n")
        print("👀 Preview (first 300 chars):")
        print("-" * 50)
        print(file_content[:300] + "..." if len(file_content) > 300 else file_content)
        print("-" * 50 + "\n")

        vectorizer, vectors = build_vectorizer(knowledge_base)
        result = simplify_and_summarize(file_content, knowledge_base, vectorizer, vectors)

        print("\n📚 RETRIEVED ANALOGIES:")
        print("-" * 50)
        for item in result["retrieved_analogies"]:
            print(f"  🔹 {item['term']} (score: {item['score']})")

        print("\n✅ SHORT SUMMARY:")
        print("=" * 60)
        print(result["summary"])
        print("=" * 60)

        base_name = os.path.splitext(filename)[0]
        output_filename = f"summary_{base_name}.txt"
        with open(output_filename, 'w', encoding='utf-8') as f:
            f.write(f"SUMMARY OF: {filename}\n")
            f.write("=" * 60 + "\n\n")
            f.write(result["summary"])

        print(f"\n💾 Downloading '{output_filename}'...")
        files.download(output_filename)
        print("✅ Done!")

